<a href="https://colab.research.google.com/github/Kirthiga19/Kirthiga19/blob/main/Random_forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving Model Sample Data - Retail Inventory.xlsx to Model Sample Data - Retail Inventory (1).xlsx

In [3]:
import pandas as pd
df = pd.read_excel('Model Sample Data - Retail Inventory.xlsx')

In [4]:
import pandas as pd

# The file 'Model Sample Data - Retail Inventory.xlsx' was uploaded.
df = pd.read_excel('Model Sample Data - Retail Inventory.xlsx')

display(df.head())

,Store Location (i),Product,Volume per unit of product (cm3),"Beginning Inventory (Bipi, pc)","Lower Maintaining Inventory Level (LMILpi, pc)","Expected Maintaining Inventory Level (EMILpi, pc)","Upper Maintaining Inventory Level (UMILpi, pc)",Product category (from Phase 1),"selling price (sp, Php/pc)","cost (cp, Php/pc)",...,"warehouse holding cost (wpi, Php/pc)","transshipment cost (tspi, Php/pc)","ordering cost (copi, Php/pc)",Weight per unit of product (g),Unnamed: 16,Sales (units),Product Reference,Unnamed: 19,"REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26",Unnamed: 21
0,1,p1,469,30,47,83,119,NDS,75,63.75,...,30.18227,0,60,55,500.0,147,PASTRY,NaN,NaN,NaN
1,Distance from Centralized Disposal Facility,p5,72,136,20,46,72,NDS,101,40.4,...,8.653497,1.35,60,57,600.0,6,COSMETICS,NaN,NaN,NaN
2,NaN,p8,366,48,49,89,128,NDS,89,75.65,...,25.583349,0,60,56,1250.0,90,COSMETICS,NaN,NaN,NaN
3,NaN,p16,393,96,35,63,90,UDS,1907.5,1750,...,26.826563,1.62,60,55,720.0,94,COSMETICS,NaN,NaN,NaN
4,NaN,p17,121,23,49,80,111,NDS,45,38.25,...,12.23189,0,60,59,500.0,79,PASTRY,NaN,NaN,NaN

In [5]:
df = pd.read_excel('Model Sample Data - Retail Inventory.xlsx')

In [6]:
display(df.describe())

,Unnamed: 16,"REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26",Unnamed: 21
count,30.0000,9.000000,9.000000
mean,795.0000,3.333333,0.333333
std,361.1834,2.500000,0.250000
min,400.0000,1.000000,0.100000
25%,500.0000,1.000000,0.100000
50%,660.0000,4.000000,0.400000
75%,1000.0000,5.000000,0.500000
max,1500.0000,8.000000,0.800000

In [7]:
import os
print(os.listdir())

['.config', 'Model Sample Data - Retail Inventory.xlsx', 'Model Sample Data - Retail Inventory (1).xlsx', 'sample_data']

In [9]:
print("Missing values in each column:\n")
display(df.isnull().sum())

Missing values in each column:

Store Location (i)                                                         18
Product                                                                     3
Volume per unit of product (cm3)                                            3
Beginning Inventory (Bipi, pc)                                              3
Lower Maintaining Inventory Level (LMILpi, pc)                              3
Expected Maintaining Inventory Level (EMILpi, pc)                           3
Upper Maintaining Inventory Level (UMILpi, pc)                              3
Product category (from Phase 1)                                             3
selling price (sp, Php/pc)                                                  3
cost (cp, Php/pc)                                                           3
disposal cost (disppi, Php/pc)                                              3
transport cost (tpi, Php/pc)                                                3
warehouse holding cost (wpi, Php/pc)                                        3
transshipment cost (tspi, Php/pc)                                           3
ordering cost (copi, Php/pc)                                                3
Weight per unit of product (g)                                              3
Unnamed: 16                                                                 5
Sales (units)                                                               3
Product Reference                                                           3
Unnamed: 19                                                                26
REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26    26
Unnamed: 21                                                                26
dtype: int64

In [10]:
import os
print(os.listdir())

['.config', 'Model Sample Data - Retail Inventory (2).xlsx', 'Model Sample Data - Retail Inventory.xlsx', 'Model Sample Data - Retail Inventory (1).xlsx', 'sample_data']

In [11]:
import numpy as np

# List of columns identified as numerical but currently of object type
columns_to_convert = [
    'Volume per unit of product (cm3)',
    'Beginning Inventory (Bipi, pc)',
    'Lower Maintaining Inventory Level (LMILpi, pc)',
    'Expected Maintaining Inventory Level (EMILpi, pc)',
    'Upper Maintaining Inventory Level (UMILpi, pc)',
    'selling price (sp, Php/pc)',
    'cost (cp, Php/pc)',
    'disposal cost (disppi, Php/pc)',
    'transport cost (tpi, Php/pc)',
    'warehouse holding cost (wpi, Php/pc)',
    'transshipment cost (tspi, Php/pc)',
    'ordering cost (copi, Php/pc)',
    'Weight per unit of product (g)',
    'Sales (units)'
]

for col in columns_to_convert:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

print("Data types after conversion:")
df.info()

Data types after conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 22 columns):
 #   Column                                                                   Non-Null Count  Dtype
---  ------                                                                   --------------  -----
 0   Store Location (i)                                                       17 non-null     object
 1   Product                                                                  32 non-null     object
 2   Volume per unit of product (cm3)                                         30 non-null     float64
 3   Beginning Inventory (Bipi, pc)                                           30 non-null     float64
 4   Lower Maintaining Inventory Level (LMILpi, pc)                           30 non-null     float64
 5   Expected Maintaining Inventory Level (EMILpi, pc)                        30 non-null     float64
 6   Upper Maintaining Inventory Level (UMILpi, pc)                           30 non-null     float64
 7   Product category (from Phase 1)                                          32 non-null     object
 8   selling price (sp, Php/pc)                                               30 non-null     float64
 9   cost (cp, Php/pc)                                                        30 non-null     float64
 10  disposal cost (disppi, Php/pc)                                           30 non-null     float64
 11  transport cost (tpi, Php/pc)                                             30 non-null     float64
 12  warehouse holding cost (wpi, Php/pc)                                     30 non-null     float64
 13  transshipment cost (tspi, Php/pc)                                        30 non-null     float64
 14  ordering cost (copi, Php/pc)                                             30 non-null     float64
 15  Weight per unit of product (g)                                           30 non-null     float64
 16  Unnamed: 16                                                              30 non-null     float64
 17  Sales (units)                                                            30 non-null     float64
 18  Product Reference                                                        32 non-null     object
 19  Unnamed: 19                                                              9 non-null      object
 20  REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26  9 non-null      float64
 21  Unnamed: 21                                                              9 non-null      float64
dtypes: float64(17), object(5)
memory usage: 6.1+ KB

In [12]:
print("Descriptive statistics for numerical columns after conversion:")
display(df.describe())

Descriptive statistics for numerical columns after conversion:

,Volume per unit of product (cm3),"Beginning Inventory (Bipi, pc)","Lower Maintaining Inventory Level (LMILpi, pc)","Expected Maintaining Inventory Level (EMILpi, pc)","Upper Maintaining Inventory Level (UMILpi, pc)","selling price (sp, Php/pc)","cost (cp, Php/pc)","disposal cost (disppi, Php/pc)","transport cost (tpi, Php/pc)","warehouse holding cost (wpi, Php/pc)","transshipment cost (tspi, Php/pc)","ordering cost (copi, Php/pc)",Weight per unit of product (g),Unnamed: 16,Sales (units),"REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26",Unnamed: 21
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.0000,30.000000,9.000000,9.000000
mean,221.200000,77.700000,46.500000,76.066667,105.066667,588.233000,525.440000,13.144793,8.374000,17.016733,1.687500,66.666667,64.233333,795.0000,151.036667,3.333333,0.333333
std,158.729308,32.361269,17.832071,19.199377,22.408332,806.047837,748.469078,6.498321,3.819139,9.303302,1.863813,9.589266,10.005803,361.1834,146.384328,2.500000,0.250000
min,54.000000,23.000000,19.000000,40.000000,61.000000,9.000000,7.650000,5.615433,4.030000,5.428912,0.000000,60.000000,55.000000,400.0000,4.000000,1.000000,0.100000
25%,92.000000,56.500000,38.500000,63.750000,88.500000,45.000000,38.250000,7.674425,5.262500,9.472213,0.000000,60.000000,56.250000,500.0000,40.000000,1.000000,0.100000
50%,128.000000,72.500000,45.500000,80.000000,106.000000,95.000000,59.875000,10.538296,6.927000,13.256031,1.568000,60.000000,59.000000,660.0000,131.500000,4.000000,0.400000
75%,393.000000,92.500000,56.250000,85.750000,119.750000,1633.910000,1499.000000,16.904793,10.881250,24.922143,2.556000,80.000000,75.750000,1000.0000,181.250000,5.000000,0.500000
max,469.000000,154.000000,104.000000,119.000000,138.000000,1907.500000,1750.000000,30.884882,16.500000,36.218724,6.600000,80.000000,80.000000,1500.0000,639.000000,8.000000,0.800000

In [8]:
from google.colab import files
uploaded = files.upload()

Saving Model Sample Data - Retail Inventory.xlsx to Model Sample Data - Retail Inventory (2).xlsx

In [13]:
print(os.listdir())

['.config', 'Model Sample Data - Retail Inventory (2).xlsx', 'Model Sample Data - Retail Inventory.xlsx', 'Model Sample Data - Retail Inventory (1).xlsx', 'sample_data']

In [14]:
print("Missing values in each column:")
display(df.isnull().sum())

Missing values in each column:

Store Location (i)                                                         18
Product                                                                     3
Volume per unit of product (cm3)                                            5
Beginning Inventory (Bipi, pc)                                              5
Lower Maintaining Inventory Level (LMILpi, pc)                              5
Expected Maintaining Inventory Level (EMILpi, pc)                           5
Upper Maintaining Inventory Level (UMILpi, pc)                              5
Product category (from Phase 1)                                             3
selling price (sp, Php/pc)                                                  5
cost (cp, Php/pc)                                                           5
disposal cost (disppi, Php/pc)                                              5
transport cost (tpi, Php/pc)                                                5
warehouse holding cost (wpi, Php/pc)                                        5
transshipment cost (tspi, Php/pc)                                           5
ordering cost (copi, Php/pc)                                                5
Weight per unit of product (g)                                              5
Unnamed: 16                                                                 5
Sales (units)                                                               5
Product Reference                                                           3
Unnamed: 19                                                                26
REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26    26
Unnamed: 21                                                                26
dtype: int64

In [15]:
print("Missing values in each column:")
display(df.isnull().sum())

Missing values in each column:

Store Location (i)                                                         18
Product                                                                     3
Volume per unit of product (cm3)                                            5
Beginning Inventory (Bipi, pc)                                              5
Lower Maintaining Inventory Level (LMILpi, pc)                              5
Expected Maintaining Inventory Level (EMILpi, pc)                           5
Upper Maintaining Inventory Level (UMILpi, pc)                              5
Product category (from Phase 1)                                             3
selling price (sp, Php/pc)                                                  5
cost (cp, Php/pc)                                                           5
disposal cost (disppi, Php/pc)                                              5
transport cost (tpi, Php/pc)                                                5
warehouse holding cost (wpi, Php/pc)                                        5
transshipment cost (tspi, Php/pc)                                           5
ordering cost (copi, Php/pc)                                                5
Weight per unit of product (g)                                              5
Unnamed: 16                                                                 5
Sales (units)                                                               5
Product Reference                                                           3
Unnamed: 19                                                                26
REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26    26
Unnamed: 21                                                                26
dtype: int64

In [16]:
print("First 5 rows of the DataFrame:")
display(df.head())

First 5 rows of the DataFrame:

,Store Location (i),Product,Volume per unit of product (cm3),"Beginning Inventory (Bipi, pc)","Lower Maintaining Inventory Level (LMILpi, pc)","Expected Maintaining Inventory Level (EMILpi, pc)","Upper Maintaining Inventory Level (UMILpi, pc)",Product category (from Phase 1),"selling price (sp, Php/pc)","cost (cp, Php/pc)",...,"warehouse holding cost (wpi, Php/pc)","transshipment cost (tspi, Php/pc)","ordering cost (copi, Php/pc)",Weight per unit of product (g),Unnamed: 16,Sales (units),Product Reference,Unnamed: 19,"REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26",Unnamed: 21
0,1,p1,469.0,30.0,47.0,83.0,119.0,NDS,75.0,63.75,...,30.182270,0.00,60.0,55.0,500.0,147.0,PASTRY,NaN,NaN,NaN
1,Distance from Centralized Disposal Facility,p5,72.0,136.0,20.0,46.0,72.0,NDS,101.0,40.40,...,8.653497,1.35,60.0,57.0,600.0,6.0,COSMETICS,NaN,NaN,NaN
2,NaN,p8,366.0,48.0,49.0,89.0,128.0,NDS,89.0,75.65,...,25.583349,0.00,60.0,56.0,1250.0,90.0,COSMETICS,NaN,NaN,NaN
3,NaN,p16,393.0,96.0,35.0,63.0,90.0,UDS,1907.5,1750.00,...,26.826563,1.62,60.0,55.0,720.0,94.0,COSMETICS,NaN,NaN,NaN
4,NaN,p17,121.0,23.0,49.0,80.0,111.0,NDS,45.0,38.25,...,12.231890,0.00,60.0,59.0,500.0,79.0,PASTRY,NaN,NaN,NaN

In [17]:
import os
import zipfile
import pandas as pd

# First, let's see what files are currently in your directory.
# This helps you identify the exact name of your uploaded zip file.
print("Files in current directory:")
print(os.listdir())

# --- Replace 'your_zip_file.zip' with the actual name of your zip file ---
zip_file_name = 'Retail Inventory Data (1).zip' # Example zip file name
# If you have another zip file, update this variable accordingly

# Create a directory to extract files into (optional but good practice)
extraction_path = 'extracted_data'
os.makedirs(extraction_path, exist_ok=True)

try:
    with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
        zip_ref.extractall(extraction_path)
    print(f"\nSuccessfully extracted '{zip_file_name}' to '{extraction_path}'.")

    # List files inside the extracted directory to find your data file
    print(f"\nFiles in '{extraction_path}' after extraction:")
    print(os.listdir(extraction_path))

    # --- Assuming your data is in a CSV file named 'your_data.csv' inside the zip ---
    # --- You'll need to replace 'your_data.csv' with the actual name of your data file ---
    data_file_in_zip = 'file_name_inside_zip.csv' # Example data file name
    full_file_path = os.path.join(extraction_path, data_file_in_zip)

    if os.path.exists(full_file_path):
        # Check if it's a CSV or Excel and use the appropriate pandas function
        if data_file_in_zip.endswith('.csv'):
            df_from_zip = pd.read_csv(full_file_path)
            print(f"\nSuccessfully loaded '{data_file_in_zip}' into a DataFrame.")
            display(df_from_zip.head())
        elif data_file_in_zip.endswith('.xlsx') or data_file_in_zip.endswith('.xls'):
            df_from_zip = pd.read_excel(full_file_path)
            print(f"\nSuccessfully loaded '{data_file_in_zip}' into a DataFrame.")
            display(df_from_zip.head())
        else:
            print(f"Unsupported file type for '{data_file_in_zip}'. Please load manually.")
    else:
        print(f"\nError: Data file '{data_file_in_zip}' not found in '{extraction_path}'. Please check the filename inside your zip.")

except FileNotFoundError:
    print(f"\nError: The zip file '{zip_file_name}' was not found. Please ensure it's uploaded or the name is correct.")
except Exception as e:
    print(f"\nAn unexpected error occurred: {e}")

Files in current directory:
['.config', 'Model Sample Data - Retail Inventory (2).xlsx', 'Model Sample Data - Retail Inventory.xlsx', 'Model Sample Data - Retail Inventory (1).xlsx', 'sample_data']

Error: The zip file 'Retail Inventory Data (1).zip' was not found. Please ensure it's uploaded or the name is correct.

In [18]:
print("First 5 rows of the DataFrame:")
display(df.head())

First 5 rows of the DataFrame:

,Store Location (i),Product,Volume per unit of product (cm3),"Beginning Inventory (Bipi, pc)","Lower Maintaining Inventory Level (LMILpi, pc)","Expected Maintaining Inventory Level (EMILpi, pc)","Upper Maintaining Inventory Level (UMILpi, pc)",Product category (from Phase 1),"selling price (sp, Php/pc)","cost (cp, Php/pc)",...,"warehouse holding cost (wpi, Php/pc)","transshipment cost (tspi, Php/pc)","ordering cost (copi, Php/pc)",Weight per unit of product (g),Unnamed: 16,Sales (units),Product Reference,Unnamed: 19,"REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26",Unnamed: 21
0,1,p1,469.0,30.0,47.0,83.0,119.0,NDS,75.0,63.75,...,30.182270,0.00,60.0,55.0,500.0,147.0,PASTRY,NaN,NaN,NaN
1,Distance from Centralized Disposal Facility,p5,72.0,136.0,20.0,46.0,72.0,NDS,101.0,40.40,...,8.653497,1.35,60.0,57.0,600.0,6.0,COSMETICS,NaN,NaN,NaN
2,NaN,p8,366.0,48.0,49.0,89.0,128.0,NDS,89.0,75.65,...,25.583349,0.00,60.0,56.0,1250.0,90.0,COSMETICS,NaN,NaN,NaN
3,NaN,p16,393.0,96.0,35.0,63.0,90.0,UDS,1907.5,1750.00,...,26.826563,1.62,60.0,55.0,720.0,94.0,COSMETICS,NaN,NaN,NaN
4,NaN,p17,121.0,23.0,49.0,80.0,111.0,NDS,45.0,38.25,...,12.231890,0.00,60.0,59.0,500.0,79.0,PASTRY,NaN,NaN,NaN

In [19]:
print("DataFrame Info (data types and non-null counts):")
df.info()

DataFrame Info (data types and non-null counts):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 22 columns):
 #   Column                                                                   Non-Null Count  Dtype
---  ------                                                                   --------------  -----
 0   Store Location (i)                                                       17 non-null     object
 1   Product                                                                  32 non-null     object
 2   Volume per unit of product (cm3)                                         30 non-null     float64
 3   Beginning Inventory (Bipi, pc)                                           30 non-null     float64
 4   Lower Maintaining Inventory Level (LMILpi, pc)                           30 non-null     float64
 5   Expected Maintaining Inventory Level (EMILpi, pc)                        30 non-null     float64
 6   Upper Maintaining Inventory Level (UMILpi, pc)                           30 non-null     float64
 7   Product category (from Phase 1)                                          32 non-null     object
 8   selling price (sp, Php/pc)                                               30 non-null     float64
 9   cost (cp, Php/pc)                                                        30 non-null     float64
 10  disposal cost (disppi, Php/pc)                                           30 non-null     float64
 11  transport cost (tpi, Php/pc)                                             30 non-null     float64
 12  warehouse holding cost (wpi, Php/pc)                                     30 non-null     float64
 13  transshipment cost (tspi, Php/pc)                                        30 non-null     float64
 14  ordering cost (copi, Php/pc)                                             30 non-null     float64
 15  Weight per unit of product (g)                                           30 non-null     float64
 16  Unnamed: 16                                                              30 non-null     float64
 17  Sales (units)                                                            30 non-null     float64
 18  Product Reference                                                        32 non-null     object
 19  Unnamed: 19                                                              9 non-null      object
 20  REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26  9 non-null      float64
 21  Unnamed: 21                                                              9 non-null      float64
dtypes: float64(17), object(5)
memory usage: 6.1+ KB

In [20]:
print("Descriptive statistics for numerical columns:")
display(df.describe())

Descriptive statistics for numerical columns:

,Volume per unit of product (cm3),"Beginning Inventory (Bipi, pc)","Lower Maintaining Inventory Level (LMILpi, pc)","Expected Maintaining Inventory Level (EMILpi, pc)","Upper Maintaining Inventory Level (UMILpi, pc)","selling price (sp, Php/pc)","cost (cp, Php/pc)","disposal cost (disppi, Php/pc)","transport cost (tpi, Php/pc)","warehouse holding cost (wpi, Php/pc)","transshipment cost (tspi, Php/pc)","ordering cost (copi, Php/pc)",Weight per unit of product (g),Unnamed: 16,Sales (units),"REMOVED PRODUCTS: 2,3,4,6,7,9,10,11,12,14,15,13,19,20,22,23, 24, 25, 26",Unnamed: 21
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000,30.0000,30.000000,9.000000,9.000000
mean,221.200000,77.700000,46.500000,76.066667,105.066667,588.233000,525.440000,13.144793,8.374000,17.016733,1.687500,66.666667,64.233333,795.0000,151.036667,3.333333,0.333333
std,158.729308,32.361269,17.832071,19.199377,22.408332,806.047837,748.469078,6.498321,3.819139,9.303302,1.863813,9.589266,10.005803,361.1834,146.384328,2.500000,0.250000
min,54.000000,23.000000,19.000000,40.000000,61.000000,9.000000,7.650000,5.615433,4.030000,5.428912,0.000000,60.000000,55.000000,400.0000,4.000000,1.000000,0.100000
25%,92.000000,56.500000,38.500000,63.750000,88.500000,45.000000,38.250000,7.674425,5.262500,9.472213,0.000000,60.000000,56.250000,500.0000,40.000000,1.000000,0.100000
50%,128.000000,72.500000,45.500000,80.000000,106.000000,95.000000,59.875000,10.538296,6.927000,13.256031,1.568000,60.000000,59.000000,660.0000,131.500000,4.000000,0.400000
75%,393.000000,92.500000,56.250000,85.750000,119.750000,1633.910000,1499.000000,16.904793,10.881250,24.922143,2.556000,80.000000,75.750000,1000.0000,181.250000,5.000000,0.500000
max,469.000000,154.000000,104.000000,119.000000,138.000000,1907.500000,1750.000000,30.884882,16.500000,36.218724,6.600000,80.000000,80.000000,1500.0000,639.000000,8.000000,0.800000